version: '3.8'

services:
  springapp:
    build: 
      context: ./Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mydb  # MongoDB connection URI

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Mount a volume for MongoDB data persistence

volumes:
  mongodb_data:  # Define the volume for MongoDB data persistence
