version: '3'

services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  spring-app:
    image: tp-devops:latest
    container_name: my_spring_app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: your_database_name

volumes:
  mongodb_data:
    driver: local
